spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: 27017
      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: admin

token:
  signing:
    key: ${TOKEN_KEY}

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.soyummy: DEBUG